// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPnGlR8R_RviuqjzeqEeq3sYRCckbYpiI',
    appId: '1:439934674216:web:fb5bd84c2b6485810d1c1d',
    messagingSenderId: '439934674216',
    projectId: 'fiesc-my-book-store',
    authDomain: 'fiesc-my-book-store.firebaseapp.com',
    storageBucket: 'fiesc-my-book-store.firebasestorage.app',
    measurementId: 'G-5Y35ZS702R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXAKysyAT15sZlGQ5qLj_QtaBROjEuIm0',
    appId: '1:439934674216:android:bcc870b03b78104e0d1c1d',
    messagingSenderId: '439934674216',
    projectId: 'fiesc-my-book-store',
    storageBucket: 'fiesc-my-book-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcQYZlSZ6Rz6m3qpVcUdBb4_3skuNhD0c',
    appId: '1:439934674216:ios:359ec8b7d7d84dc40d1c1d',
    messagingSenderId: '439934674216',
    projectId: 'fiesc-my-book-store',
    storageBucket: 'fiesc-my-book-store.firebasestorage.app',
    iosBundleId: 'com.example.mybookstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcQYZlSZ6Rz6m3qpVcUdBb4_3skuNhD0c',
    appId: '1:439934674216:ios:359ec8b7d7d84dc40d1c1d',
    messagingSenderId: '439934674216',
    projectId: 'fiesc-my-book-store',
    storageBucket: 'fiesc-my-book-store.firebasestorage.app',
    iosBundleId: 'com.example.mybookstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPnGlR8R_RviuqjzeqEeq3sYRCckbYpiI',
    appId: '1:439934674216:web:438ef967117299d40d1c1d',
    messagingSenderId: '439934674216',
    projectId: 'fiesc-my-book-store',
    authDomain: 'fiesc-my-book-store.firebaseapp.com',
    storageBucket: 'fiesc-my-book-store.firebasestorage.app',
    measurementId: 'G-0WLXEGKZW6',
  );
}
